### ISSUE TITLE
download https url doesn't get status code

### ISSUE THREAD

**Issue by BeyondIM** [negrutiu/nsis-nsxfer#1]
Thank you for developing such a good plug-in, but download https url doesn't get status code

![2019-12-22-103440_615x474_scrot.png](https://i.loli.net/2019/12/22/F2jR3ZPU6JOvh7D.png)

**Comment by negrutiu** [comment]
The status is read from server's response headers.
It turned out that your server doesn't return the status text (aka Reason-Phrase) in its response Status-Line.
I've modified the plugin to handle this. Check out the latest release!
Thank you for reporting the problem.
