### ISSUE TITLE
How to retrieve memory content?

### ISSUE THREAD

**Issue by BeyondIM** [negrutiu/nsis-nsxfer#2]
Thank you for this great plugin. I noticed this plugin could download remote content to memory buffer, but how to retrieve memory content to Nsis script? 

And I noticed you develop another plugin nsis-nscurl, which is best?

**Comment by negrutiu** [comment]
You can retrieve the memory content like this:
```nsis
NSxfer::Request /URL "https://httpbin.org/get?param1=1&param2=2" /LOCAL memory /END
Pop $0		; Transfer ID
NSxfer::Wait /ID $0
Pop $1		; Wait for transfer to complete
NSxfer::Query /ID $0 /CONTENT /END
Pop $1		; Remote-content as string truncated to ${NSIS_MAX_STRLEN}. Empty string in case of errors
DetailPrint 'Remote-Content: "$1"'
```

Indeed, I've switched developent to [NScurl](https://github.com/negrutiu/nsis-nscurl).
It's built on top of [libcurl](https://curl.haxx.se/libcurl) which I think it's far superior to the native windows API.
With `NScurl` the same code would look like:
```nsis
NScurl::http GET "https://httpbin.org/get?param1=1&param2=2" "MEMORY" /RETURN "@recvdata@" /END
Pop $0
DetailPrint 'Remote-Content: "$0"'
```

`NScurl` is newer and better. I recommend it.
Thanks for your kind words and enjoy my NSIS plugin(s)...

**Comment by BeyondIM** [comment]
The code has been working perfectly before, but recently when I migrate my domain name to cloudflare, the code couldn't get memory content, It show `Remote-Content: ""`.Is there any way to solve this problem?

Thank you very much.
