### ISSUE TITLE
Stack Corruption Issue

### ISSUE THREAD

**Issue by sopadelata** [negrutiu/nsis-nsxfer#9]
Hello,

Thanks for the great plugin.

I'm having an issue where calling NSxfer is causing stack corruption. I'm using the x86-unicode version v1.2023.4.9 with NSIS v3.08.

I was having an issue with $0 not being set to the correct value after calling a function, so I used the [Debug](https://nsis.sourceforge.io/Debug_plug-in) plugin to take a look.

It looks like the stack is being emptied or having things placed back in it unpredictably after calling the plugin.

I pushed a bunch of strings containing "Stack test", then call the plugin, and then use `Debug::Stack` to check the stack.

Here's the stack immediately before `NSxfer::Transfer`:
![image](https://github.com/negrutiu/nsis-nsxfer/assets/104468204/6ed30630-c33c-470e-83d4-69952f9bbf6a)

Here's the stack immediately after:
![image](https://github.com/negrutiu/nsis-nsxfer/assets/104468204/c2205403-1ebe-41e1-95ff-40eeeb6304cd)

As you can see, the only thing on the stack any more is the RETURNID from the plugin.

Here's the code I'm using to call the plugin in this case:
`NSxfer::Transfer /MODE SILENT /URL "http://127.0.0.1:9100/transmission/rpc/" /METHOD "GET" /LOCAL "MEMORY" /RETURNID`

The whole NSIS script: https://gist.github.com/sopadelata/7e34387adf4d411e00d0cb8df511b2f2#file-gistfile1-txt-L162

(relevant part @ line 162)

**Comment by sopadelata** [comment]
Nevermind, I'm an idiot and didn't read the readme...

**Comment by negrutiu** [comment]
Let me guess, no `/end` ? :)
Don't worry it happened to me too
Thanks for reporting anyway and enjoy the plugin!
